backend:
  name: github
  repo: dancormier/dancormier.com-v4

media_folder: content/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/index.md"
        fields:
          - {label: "Type", name: "type", widget: "hidden", default: "index"}
          - {label: Body, name: body, widget: markdown }